### ISSUE TITLE
Can you publish the source code ?

### ISSUE THREAD

**Issue by xiaolai2020** [mohammadrezanaderi4/SFI-Swin#1]
It is a great job and I am very interested in it. I want to download your code. But  I do not find it.Can you publish the source code?

**Comment by mohammadrezanaderi4** [comment]
Dear @xiaolai2020, thanks for your interest. 
We will publish the implementation as soon as we get the journal acception for our paper. 
Thanks for your patience.

**Comment by xiaolai2020** [comment]
Thank you. Looking forward to a good news!
